GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"Go to Class"
}

###
DELETE http://localhost:3001/todo/delete/639f899f6b79fc2c60ba1bb4

###
PUT http://localhost:3001/todo/complete/639f8a6f17c99b1d7c51659e

###

GET http://localhost:3001/todo/complete/639f8a6f17c99b1d7c51659e